### ISSUE TITLE
Can't run empty project with owl dependency in js_of_ocaml

### ISSUE THREAD

**Issue by philzook58** [owlbarn/owl#437]
Hi, I can't get an empty project with owl listed as a dependency to actually run using js_of_ocaml. I was hoping to use Owl_base as described here https://ocaml.xyz/chapter/javascript.html

Owl version 0.6.0
Compiler: 4.07.1
OS : Mac 10.14.6

Commands run:
```
dune build main.bc.js
node test.js
```

dune file
```
(executable
 (name main)
 (libraries js_of_ocaml owl)
 (preprocess (pps js_of_ocaml-ppx))
 )
```

main.ml empty

test.js
```
var v = require("./_build/default/main.bc.js");
```

Resulting error
```
/Users/philip/Documents/ocaml/owl_error/_build/default/main.bc.js:29195
    runtime.integers_unsigned_init(0);
            ^

TypeError: runtime.integers_unsigned_init is not a function
    at /Users/philip/Documents/ocaml/owl_error/_build/default/main.bc.js:29195:13
    at Object.<anonymous> (/Users/philip/Documents/ocaml/owl_error/_build/default/main.bc.js:30198:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/philip/Documents/ocaml/owl_error/test.js:1:71
```

Any suggestions?

**Comment by mseri** [comment]
`owl` binds lots of C libraries, it cannot work with `js_of_ocaml`. The error you see itks due to integers (dependency of ctypes) being compiled tojs_of_ocaml but missing the c external calls. 

You need to link against `owl-base` if you want to target javascript

**Comment by mseri** [comment]
We need to update the tutorial, you can find a more complex (and working) example here: https://github.com/mseri/owlde-demo-icfp2019/tree/master/teaching_material

**Comment by ryanrhymes** [comment]
@mseri Yes I agree. The whole tutorial needs to be updated and synced with current development.

**Comment by philzook58** [comment]
Thank you! I suspected there was a simple answer!
