### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by zbroyar** [owlbarn/owl#457]
Hi,

I have a pretty big matrix (763029x22716) of float64. It is stored in a file and mapped into memory with Unix.map_file (please, see [the gist](https://gist.github.com/zbroyar/3a4f768ce09498282a4f308d8ad5fa6c) for implementation details)

When I try to get a slice of the matrix the program dies with SIGSEGV. The actual code looks like this:
```
  let data = genarray_of_array2 @@ CMMap.connect ~cols:22716 fn in
  let r,c = Mat.shape data in
  printf "Mat.shape = [%d; %d]\n%!" r c;
  let start = 0 and stop = 130000 and i = 1 in
  let slice = Mat.get_slice [[start; stop]; [i]] data (* dies here *)
```

The `connect()` function is pretty simple:
```
  let connect ?rows ?cols fname =
    let rows,cols = determine_dims kind fname (rows,cols) in
    let mfile = openfile fname [O_RDWR] 0o600 in
    let data =
      array2_of_genarray @@
      Unix.map_file mfile kind layout true [|rows; cols|] in
    Hashtbl.add tbl data mfile; data
```

Backtrace points to [this line](https://github.com/owlbarn/owl/blob/master/src/owl/core/owl_slicing_basic_impl.h#L55) of Owl code:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  c_float64_ndarray_get_slice_2 (p=<optimized out>) at src/owl/core/owl_slicing_basic_impl.h:55
55      src/owl/core/owl_slicing_basic_impl.h: No such file or directory.
[Current thread is 1 (Thread 0x15367d9ba740 (LWP 30887))]
(gdb) bt
#0  c_float64_ndarray_get_slice_2 (p=<optimized out>) at src/owl/core/owl_slicing_basic_impl.h:55
#1  0x0000561562b9a905 in c_float64_ndarray_get_slice (p=p@entry=0x561563cd5d20) at src/owl/core/owl_slicing_basic_impl.h:196
#2  0x0000561562b9a9f4 in stub_float64_ndarray_get_slice (vX=23322601421440, vY=23322601419880, vZ=<optimized out>) at src/owl/core/owl_slicing_basic_impl.h:252
#3  0x000056156223cac9 in camlOwl_slicing_basic__fun_3583 () at src/owl/core/owl_slicing_basic.ml:24
#4  0x000056156223de05 in camlOwl_slicing__get_slice_array_typ_2858 () at src/owl/core/owl_slicing_basic.ml:66
#5  0x00005615621f1078 in camlPlayground__owl_mmap_205240 () at src/owl/dense/owl_dense_ndarray_generic.ml:100
#6  0x00005615621f1158 in camlPlayground__fun_311479 () at test/playground/playground.ml:361
#7  0x000056156285bca1 in camlStdlib__list__iter_1151 () at list.ml:106
#8  0x00005615621f1551 in camlPlayground__entry () at test/playground/playground.ml:357
#9  0x00005615621e01d9 in caml_program ()
#10 0x0000561562c7749c in caml_start_program ()
#11 0x0000561562c59d35 in caml_startup_common (argv=0x7fff6f2b7178, pooling=<optimized out>, pooling@entry=0) at startup.c:157
#12 0x0000561562c59d9b in caml_startup_exn (argv=<optimized out>) at startup.c:162
#13 caml_startup (argv=<optimized out>) at startup.c:167
#14 0x00005615621de71c in main (argc=<optimized out>, argv=<optimized out>) at main.c:44
(gdb)  
```

What am I doing wrong?

**Comment by mseri** [comment]
@ryanrhymes is the best person to look at this. I think SIGSEGV bug should get the priority. Last time we hit a similar bug, it was in ocaml stdlib in fact, and it was due to an integer overflow

**Comment by ryanrhymes** [comment]
@ejaasaari has reported related issue before https://github.com/owlbarn/owl/issues/337 

This is due to indexing in the underlying C impl uses int_32, which causes segfault when operating on large tensors over 4GB.

**Comment by mseri** [comment]
@ryanrhymes could we move it to int64_t when the arch supports it?

**Comment by ryanrhymes** [comment]
@zbroyar thanks for reporting this, I hope https://github.com/owlbarn/owl/pull/458 has fixed this issue. Please reopen the issue in case it does not.
